server:
  port: 8761

spring:
  cloud:
    zookeeper:
      discovery:
        enabled: true
        register: true
        instance-host: localhost
        instance-port: 8761

      connect-string: 192.168.178.128:2181
  application:
    name: zkserver


